history server, versioning and state machine removal
stackabletech/spark-operator-java pull request #11
Opened 2021-01-21 13:01 UTC by maltesander

2021-01-22 23:22 UTC, lfrancke requested changes
I have looked at most things but not all of them.
What's missing is the most important parts (e.g. SparkVersionedClusterController) but I won't get to them this weekend so I thought I'd submit what I have so far.

Most comments are style things which you can also ignore if you like,
there are some issues that need to be fixed and there are a lot of issues which I noted but which you don't have to fix if you don't really want to considering that we're probably rewriting anyway.

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfig.java
> +      if(!allowedValues.contains(value)) {
```suggestion
    if (allowedValues != null && allowedValues.size() > 0) {
      // not in allowed values
      if (!allowedValues.contains(value)) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +package tech.stackable.spark.operator.cluster.versioned;
The 2.4 and 3 controllers are the same (except for the version number). Does it not make sense to merge them into one? When you need more it's easy to then create a new one.

I'll only review this file, should I find anything the same is true for the 3 controller.

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +    if(cluster.getSpec().getLogDir() != null && !cluster.getSpec().getLogDir().isEmpty()) {
```suggestion
    if (cluster.getSpec().getLogDir() != null && !cluster.getSpec().getLogDir().isEmpty()) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +    if(selector.getMemory() != null && !selector.getMemory().isEmpty()) {
```suggestion
    if( selector.getMemory() != null && !selector.getMemory().isEmpty()) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +    if(cluster.getSpec().getLogDir() != null && !cluster.getSpec().getLogDir().isEmpty()) {
```suggestion
    if (cluster.getSpec().getLogDir() != null && !cluster.getSpec().getLogDir().isEmpty()) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +    if(selector.getCores() != null && !selector.getCores().isEmpty()) {
```suggestion
    if (selector.getCores() != null && !selector.getCores().isEmpty()) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +    if(selector.getMemory() != null && !selector.getMemory().isEmpty()) {
```suggestion
    if (selector.getMemory() != null && !selector.getMemory().isEmpty()) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +    if(cluster.getSpec().getLogDir() != null && !cluster.getSpec().getLogDir().isEmpty()) {
```suggestion
    if (cluster.getSpec().getLogDir() != null && !cluster.getSpec().getLogDir().isEmpty()) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +    if(selector.getMemory() != null && !selector.getMemory().isEmpty()) {
```suggestion
    if (selector.getMemory() != null && !selector.getMemory().isEmpty()) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +    if(secret != null && !secret.isEmpty()) {
```suggestion
    if (secret != null && !secret.isEmpty()) {
```

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerHelper.java
> +   * Check if all given pods have status "Running"
Comment is outdated

2021-01-22 23:22 UTC, lfrancke commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerHelper.java
> +  public static String convertToSparkConfig(Map<String,String> configProperties) {
This method and the next one are exactly the same apart from the separator.
Probably makes sense to extract a third method that these two delegate to and that takes a separator.

2021-01-23 20:38 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/crd/SparkClusterSpec.java
> +  private SparkNodeMaster master;
added the TODO. 
For me it represents the field in the CRD. Multiple nodes a represented via selectors and instances and handeled in lists. There are the plural names.

2021-01-24 10:54 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/command/SparkCommandController.java
> +    List<HasMetadata> metadata = loadYaml(clusterCrdPath);
i cached it -> loaded via constructor from startup

2021-01-24 10:56 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/command/SparkCommandController.java
> +  }
yes if the try block does not work the request is deleted. I do not have the "requeue" ability implemented.

2021-01-24 11:00 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +  private SparkCluster adaptVersionedClusterController(SparkCluster cluster, SparkVersionMatchLevel level) {
changed the name. 
from the logic now it defaults to the last used controller - which is bad. I did not invest too much time in the logic here.
The simple way it works now, i have no ability to abort / continue / requeue. That will need some more effort.

2021-01-24 11:07 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +          .getSparkVersionedController(cluster.getSpec().getImage(), SparkVersionMatchLevel.PATCH, getClient(), podLister, getCrdLister(), getCrdClient());
yes level should be a parameter. There are several occurrences which all use Patch which may lead to matching errors.

2021-01-24 11:08 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfigVersion.java
> +    Pattern r = Pattern.compile(REGEX);
done. Regex patterns are pre compiled now.

2021-01-24 11:10 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +      if (versionedController.getVersion().equals(new SparkConfigVersion(cluster.getStatus().getImage().getVersion()))) {
added null check

2021-01-24 11:13 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +    List<ConfigMap> deletedConfigMaps = versionedController.deleteAllClusterConfigMaps(cluster, nodes);
Yes should not happen. Its just an additional behavior to keep it clean. Unused left over pods should be deleted here to or even better ensure that no left over pods and config maps exist.

2021-01-24 11:16 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +    if (status.getRunningCommand() != null && status.getRunningCommand().getStatus() == SparkClusterCommandStatus.RUNNING) {
It checks if there is a running command and if the status of that command is "Running". It is a little bit confusing with runningCommand etc. Maybe that should be renamed. I do not see where there is a check for deletion of all commands?

2021-01-24 11:17 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +  private void removeExcessPods(SparkCluster cluster, SparkNode... nodes) {
Yes i never thought about that. And before the history server introduction it would not come up like that. I think if you specify a spark cluster you WILL specify masters and workers. But it is definitely true. Im not sure if its worth the effort to change it now?

2021-01-24 11:21 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +        }
Yes. To start workers (not history-server) you need to provide the hostname or ip of the master.
"./start-worker.sh spark://master_ip:master_port,...."
The agent sets the hostname with a little delay, so to make sure the hostname exists there is a wait (maybe wait for master running is a bit much, could be replaced by wait for master hostnames...)
I had problems with multiple masters not running and starting workers, so i just made sure here it wont happen.
It was considered with who is the master leader etc. 
But you can give the workers a list of all masters (which is done in the code) so that is not an issue anymore.

2021-01-24 11:22 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +        // create master instances if required
yes, outdated command removed :)

2021-01-24 11:23 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +      }
No the inner logic is a create or replace. So if it exists itll get overwritten with updated values.

2021-01-24 11:25 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +  private void createConfigMaps(SparkCluster cluster, SparkNode... nodes) {
Yeah the long if statement in the beginning just makes sure no commands like restart etc are executed. I dont have requeue or abort in that logic, so it needs to be there to not start to reconcile once we updated or restart.

2021-01-24 11:27 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/SparkClusterController.java
> +    if (cluster.getStatus() == null ||
Yes overall there are probably more than one similar checks like that. Helper function could make sense. I waited to have the overall logic together and eventually improve the process method with returns and requeues.

2021-01-24 11:31 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfigProperty.java
> +   * config property name (format a.b.c...)
Yeah i thought about that too. Not sure what the common ground here is. Id prefer to have abstract methods / interfaces / traits that implement the logic for each product config. Ill think more about that when implementing the Rust part

2021-01-24 11:32 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfigProperty.java
> +  private final String importance;
Yeah i was not really using that here anyways so it was a string. Will change for Rust.

2021-01-24 11:32 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfigProperty.java
> +  private final String submit;
Yeah will think about that for Rust.

2021-01-24 11:35 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfigProperty.java
> +    return configProperty.replaceAll(Pattern.quote(CONF_SEPARATOR), ENV_SEPARATOR).toUpperCase();
You can not. I experimented a bit with spark. Some are convertible, some are not. I did not find any references / configuration help that might specify that. So its try / error or in my opinion better to keep config and env seperated unless we really need it and test it first. So for Rust i would not allow to convert a config property to be converted as env var unless both are specified in the json/yaml/csv?

2021-01-24 11:39 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfigProperty.java
> +  public String getName() {
Yeah i would be strict about that. In the Java logic and in my csv file i have either config or env names. So if i wanted to use a config property as an env var i had these "refactor" methods which return one or the other or to like replace(".","_").toUpperCase()... etc.
For Rust i would really like to keep that separated.

2021-01-24 11:41 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfigProperty.java
> +      List<String> allowedValueList = splitToList(allowedValues, LIST_SEPARATOR);
Yes. All the config code here is really spark (or even how i entered/adapted the stuff in the csv) specific. Once we move to json or similar, we wont have the problems at least with list separators etc.

2021-01-24 11:44 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfigUnit.java
> +  PASSWORD("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,32}$"),
Yes. I was playing with regex expressions. Nothing is enforced here though, just a warning is logged when its not matching.

2021-01-24 11:52 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfig.java
> +  public SparkConfigProperty getProperty(SparkConfigValue configValue) {
Should be possible. I have to test that.

2021-01-24 11:55 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/config/SparkConfig.java
> +  public String getPropertyName(String configProperty) {
No the mapping is case insensitive. So you could pass "spark_mASTer_port" and retrieve "SPARK_MASTER_PORT" as stored in the csv/json... 
Thats another thing im unsure about. I would enforce correct spelling and stop with that lower case / uppercase transformation and just throw an error if not found?

2021-01-24 11:59 UTC, maltesander commented on src/main/java/tech/stackable/spark/operator/cluster/versioned/SparkVersionedClusterControllerV247.java
> +package tech.stackable.spark.operator.cluster.versioned;
For now they are the same true. Id like to keep it separated for now, because if we really get differences via config properties we need different controllers. 
We could just merge too and use the same controller for similar versions retrieved from the factory as shown here: 
switch(version) {
      case V_2_4_0:
      case V_2_4_1:
      case V_2_4_2:
      case V_2_4_3:
      case V_2_4_4:
      case V_2_4_5:
      case V_2_4_6:
      case V_2_4_7:
        controller = new SparkVersionedClusterControllerV247(version.getVersion(), client, podLister, crdLister, crdClient);
        break;
      case V_3_0_0:
      case V_3_0_1:
        controller = new SparkVersionedClusterControllerV301(version.getVersion(), client, podLister, crdLister, crdClient);
        break;
      case NOT_SUPPORTED:
      default:
        break;
    }
So e.g. here for each 2.4.X version the 2.4.7 controller is used.

2021-02-04 09:47 UTC, lfrancke approved these changes
We decided to approve and merge this for now and then more or less immediately archive the repository as we're working on the Rust alternative.

2021-02-04 13:52 UTC, merged